version: '3.8'
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: admin123456
      MYSQL_DATABASE: bworrow_db
    ports:
      - "3307:3306"
    networks:
      - app-network
  spring-boot-app:
    build: .
    ports:
      - "9078:8080"  # เปิดพอร์ต 9090 ในเครื่อง host และ 8080 ภายใน container
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
